artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/896d99c6f240483bbfe127f22be94a7e/artifacts
end_time: 1662486598549
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 896d99c6f240483bbfe127f22be94a7e
run_uuid: 896d99c6f240483bbfe127f22be94a7e
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486598311
status: 3
tags: []
user_id: jeff
