artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/d4e4c633de00498cae37c99e2ca6162b/artifacts
end_time: 1662449859871
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: d4e4c633de00498cae37c99e2ca6162b
run_uuid: d4e4c633de00498cae37c99e2ca6162b
source_name: ''
source_type: 4
source_version: ''
start_time: 1662449859813
status: 3
tags: []
user_id: jeff
