artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/feacee703bb740799135bd6528436848/artifacts
end_time: 1662449859716
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: feacee703bb740799135bd6528436848
run_uuid: feacee703bb740799135bd6528436848
source_name: ''
source_type: 4
source_version: ''
start_time: 1662449859662
status: 3
tags: []
user_id: jeff
