from scrapy import Field, Item


class NBA_TraditionalStatsItem(Item):
    date = Field()
    team = Field()
    gp = Field()
    win = Field()
    loss = Field()
    w_pct = Field()
    mins = Field()
    pts = Field()
    fgm = Field()
    fga = Field()
    fg_pct = Field()
    fg3m = Field()
    fg3a = Field()
    fg3_pct = Field()
    ftm = Field()
    fta = Field()
    ft_pct = Field()
    oreb = Field()
    dreb = Field()
    reb = Field()
    ast = Field()
    tov = Field()
    stl = Field()
    blk = Field()
    blka = Field()
    pf = Field()
    pfd = Field()
    p_m = Field()


class NBA_AdvancedStatsItem(Item):
    date = Field()
    team = Field()
    offrtg = Field()
    defrtg = Field()
    netrtg = Field()
    ast_pct = Field()
    ast_v_tov = Field()
    ast_ratio = Field()
    oreb_pct = Field()
    dreb_pct = Field()
    reb_pct = Field()
    tov_pct = Field()
    efg_pct = Field()
    ts_pct = Field()
    pace = Field()
    pie = Field()
    poss = Field()


class NBA_FourFactorsStatsItem(Item):
    date = Field()
    team = Field()
    fta_rate = Field()
    opp_efg_pct = Field()
    opp_fta_rate = Field()
    opp_tov_pct = Field()
    opp_oreb_pct = Field()


class NBA_MiscStatsItem(Item):
    date = Field()
    team = Field()
    pts_off_tov = Field()
    second_pts = Field()
    fbps = Field()
    pitp = Field()
    opp_pts_off_tov = Field()
    opp_second_pts = Field()
    opp_fbps = Field()
    opp_pitp = Field()


class NBA_ScoringStatsItem(Item):
    date = Field()
    team = Field()
    pct_fga_2pt = Field()
    pct_fga_3pt = Field()
    pct_pts_2pt = Field()
    pct_pts_2pt_mid = Field()
    pct_pts_3pt = Field()
    pct_pts_fbps = Field()
    pct_pts_ft = Field()
    pct_pts_off_tov = Field()
    pct_pts_pitp = Field()
    pct_ast_2fgm = Field()
    pct_uast_2fgm = Field()
    pct_ast_3fgm = Field()
    pct_uast_3fgm = Field()
    pct_ast_fgm = Field()
    pct_uast_fgm = Field()


class NBA_OpponentStatsItem(Item):
    date = Field()
    team = Field()
    opp_fgm = Field()
    opp_fga = Field()
    opp_fg_pct = Field()
    opp_3pm = Field()
    opp_3pa = Field()
    opp_3pt_pct = Field()
    opp_ftm = Field()
    opp_fta = Field()
    opp_ft_pct = Field()
    opp_oreb = Field()
    opp_dreb = Field()
    opp_reb = Field()
    opp_ast = Field()
    opp_tov = Field()
    opp_stl = Field()
    opp_blk = Field()
    opp_blka = Field()
    opp_pf = Field()
    opp_pfd = Field()
    opp_pts = Field()
    opp_pm = Field()


class NBA_SpeedDistanceStatsItem(Item):
    date = Field()
    team = Field()
    dist_feet = Field()
    dist_miles = Field()
    dist_miles_off = Field()
    dist_miles_def = Field()
    avg_speed = Field()
    avg_speed_off = Field()
    avg_speed_def = Field()


class NBA_ShootingStatsItem(Item):
    date = Field()
    team = Field()
    fgm_ra = Field()
    fga_ra = Field()
    fg_pct_ra = Field()
    fgm_paint = Field()
    fga_paint = Field()
    fg_pct_paint = Field()
    fgm_mr = Field()
    fga_mr = Field()
    fg_pct_mr = Field()
    fgm_lc3 = Field()
    fga_lc3 = Field()
    fg_pct_lc3 = Field()
    fgm_rc3 = Field()
    fga_rc3 = Field()
    fg_pct_rc3 = Field()
    fgm_c3 = Field()
    fga_c3 = Field()
    fg_pct_c3 = Field()
    fgm_atb3 = Field()
    fga_atb3 = Field()
    fg_pct_atb3 = Field()


class NBA_OpponentShootingStatsItem(Item):
    date = Field()
    team = Field()
    opp_fgm_ra = Field()
    opp_fga_ra = Field()
    opp_fg_pct_ra = Field()
    opp_fgm_paint = Field()
    opp_fga_paint = Field()
    opp_fg_pct_paint = Field()
    opp_fgm_mr = Field()
    opp_fga_mr = Field()
    opp_fg_pct_mr = Field()
    opp_fgm_lc3 = Field()
    opp_fga_lc3 = Field()
    opp_fg_pct_lc3 = Field()
    opp_fgm_rc3 = Field()
    opp_fga_rc3 = Field()
    opp_fg_pct_rc3 = Field()
    opp_fgm_c3 = Field()
    opp_fga_c3 = Field()
    opp_fg_pct_c3 = Field()
    opp_fgm_atb3 = Field()
    opp_fga_atb3 = Field()
    opp_fg_pct_atb3 = Field()


class NBA_HustleStatsItem(Item):
    date = Field()
    team = Field()
    screen_ast = Field()
    screen_ast_pts = Field()
    deflections = Field()
    off_loose_ball_rec = Field()
    def_loose_ball_rec = Field()
    loose_ball_rec = Field()
    pct_loose_ball_rec_off = Field()
    pct_loose_ball_rec_def = Field()
    charges_drawn = Field()
    contested_2pt = Field()
    contested_3pt = Field()
    contested_shots = Field()
