artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/c3e14ee2128846a2b13c34d83a5a6961/artifacts
end_time: 1662486169207
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c3e14ee2128846a2b13c34d83a5a6961
run_uuid: c3e14ee2128846a2b13c34d83a5a6961
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486169143
status: 3
tags: []
user_id: jeff
