artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/65fa338a97464c2abf515dccd8ef3705/artifacts
end_time: 1662486170945
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 65fa338a97464c2abf515dccd8ef3705
run_uuid: 65fa338a97464c2abf515dccd8ef3705
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486170881
status: 3
tags: []
user_id: jeff
