artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/13e983ed302c4b18bdcd321f05b164c4/artifacts
end_time: 1662484702742
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 13e983ed302c4b18bdcd321f05b164c4
run_uuid: 13e983ed302c4b18bdcd321f05b164c4
source_name: ''
source_type: 4
source_version: ''
start_time: 1662484702497
status: 3
tags: []
user_id: jeff
