artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/c8b6ed28950b4f2f925460442c69c566/artifacts
end_time: 1662486470394
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c8b6ed28950b4f2f925460442c69c566
run_uuid: c8b6ed28950b4f2f925460442c69c566
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486470071
status: 3
tags: []
user_id: jeff
