artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/73618cadfb2642a2af4420db3acbd407/artifacts
end_time: 1662449857343
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 73618cadfb2642a2af4420db3acbd407
run_uuid: 73618cadfb2642a2af4420db3acbd407
source_name: ''
source_type: 4
source_version: ''
start_time: 1662449857150
status: 3
tags: []
user_id: jeff
