artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/5426e48471a046c3bbd7995b48288fc2/artifacts
end_time: 1662449857975
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 5426e48471a046c3bbd7995b48288fc2
run_uuid: 5426e48471a046c3bbd7995b48288fc2
source_name: ''
source_type: 4
source_version: ''
start_time: 1662449857918
status: 3
tags: []
user_id: jeff
