import datetime


def return_season_dates(year):
    """Returns needed date info for spiders based on year.
    Args:
        year (int): End year of season.
    Returns:
        dict: Date info. Structure:
        {"season_years": season_years,
        "start_day": start_day,
        "final_day": last_day,
        "final_month": last_month,
        "final_year": last_year}
    """
    seasons = {
        "2023": {
            "abbrv": "2022-23",
            "start": "October 18, 2022",
            "end": "April 10, 2023",
        },
        "2022": {
            "abbrv": "2021-22",
            "start": "October 19, 2021",
            "end": "April 10, 2022",
        },
        "2021": {
            "abbrv": "2020-21",
            "start": "December 22, 2020",
            "end": "May 16, 2021",
        },
        "2020": {
            "abbrv": "2019-20",
            "start": "October 22, 2019",
            "end": "August 14, 2020",
        },
        "2019": {
            "abbrv": "2018-19",
            "start": "October 16, 2018",
            "end": "April 10, 2019",
        },
        "2018": {
            "abbrv": "2017-18",
            "start": "October 17, 2017",
            "end": "April 11, 2018",
        },
        "2017": {
            "abbrv": "2016-17",
            "start": "October 25, 2016",
            "end": "April 12, 2017",
        },
        "2016": {
            "abbrv": "2015-16",
            "start": "October 27, 2015",
            "end": "April 13, 2016",
        },
        "2015": {
            "abbrv": "2014-15",
            "start": "October 28, 2014",
            "end": "April 15, 2015",
        },
        "2014": {
            "abbrv": "2013-14",
            "start": "October 29, 2013",
            "end": "April 16, 2014",
        },
        "2013": {
            "abbrv": "2012-13",
            "start": "October 30, 2012",
            "end": "April 17, 2013",
        },
        "2012": {
            "abbrv": "2011-12",
            "start": "December 25, 2011",
            "end": "April 26, 2012",
        },
        "2011": {
            "abbrv": "2010-11",
            "start": "October 26, 2010",
            "end": "April 13, 2011",
        },
        "2010": {
            "abbrv": "2009-10",
            "start": "October 27, 2009",
            "end": "April 14, 2010",
        },
    }
    start_date = datetime.datetime.strptime(seasons[str(year)]["start"], "%B %d, %Y")
    final_date = datetime.datetime.strptime(seasons[str(year)]["end"], "%B %d, %Y")
    season_years = seasons[str(year)]["abbrv"]
    last_day = final_date.day
    last_month = final_date.month
    last_year = final_date.year
    return_dict = {
        "season_years": season_years,
        "start_date": start_date,
        "final_date": final_date,
        "final_day": last_day,
        "final_month": last_month,
        "final_year": last_year,
    }
    return return_dict


HTTP_REQUEST_HEADERS = {
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-US,en;q=0.9",
    "Connection": "keep-alive",
    "If-Modified-Since": "Sat, 20 Aug 2022 18:27:38 GMT",
    "Origin": "https://www.nba.com",
    "Referer": "https://www.nba.com/",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-site",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "sec-ch-ua": '"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Linux"',
    "x-nba-stats-origin": "stats",
    "x-nba-stats-token": "true",
}

HEADER_ROWS = {
    "traditional": [
        "date",
        "team",
        "gp",
        "win",
        "loss",
        "w_pct",
        "mins",
        "pts",
        "fgm",
        "fga",
        "fg_pct",
        "fg3m",
        "fg3a",
        "fg3_pct",
        "ftm",
        "fta",
        "ft_pct",
        "oreb",
        "dreb",
        "reb",
        "ast",
        "tov",
        "stl",
        "blk",
        "blka",
        "pf",
        "pfd",
        "p_m",
    ],
    "advanced": [
        "date",
        "team",
        "offrtg",
        "defrtg",
        "netrtg",
        "ast_pct",
        "ast_v_tov",
        "ast_ratio",
        "oreb_pct",
        "dreb_pct",
        "reb_pct",
        "tov_pct",
        "efg_pct",
        "ts_pct",
        "pace",
        "pie",
        "poss",
    ],
    "four_factors": [
        "date",
        "team",
        "fta_rate",
        "opp_efg_pct",
        "opp_fta_rate",
        "opp_tov_pct",
        "opp_oreb_pct",
    ],
    "misc": [
        "date",
        "team",
        "pts_off_tov",
        "second_pts",
        "fbps",
        "pitp",
        "opp_pts_off_tov",
        "opp_second_pts",
        "opp_fbps",
        "opp_pitp",
    ],
    "scoring": [
        "date",
        "team",
        "pct_fga_2pt",
        "pct_fga_3pt",
        "pct_pts_2pt",
        "pct_pts_2pt_mid",
        "pct_pts_3pt",
        "pct_pts_fbps",
        "pct_pts_ft",
        "pct_pts_off_tov",
        "pct_pts_pitp",
        "pct_ast_2fgm",
        "pct_uast_2fgm",
        "pct_ast_3fgm",
        "pct_uast_3fgm",
        "pct_ast_fgm",
        "pct_uast_fgm",
    ],
    "opponent": [
        "date",
        "team",
        "opp_fgm",
        "opp_fga",
        "opp_fg_pct",
        "opp_3pm",
        "opp_3pa",
        "opp_3pt_pct",
        "opp_ftm",
        "opp_fta",
        "opp_ft_pct",
        "opp_oreb",
        "opp_dreb",
        "opp_reb",
        "opp_ast",
        "opp_tov",
        "opp_stl",
        "opp_blk",
        "opp_blka",
        "opp_pf",
        "opp_pfd",
        "opp_pts",
        "opp_pm",
    ],
    "speed_distance": [
        "date",
        "team",
        "dist_feet",
        "dist_miles",
        "dist_miles_off",
        "dist_miles_def",
        "avg_speed",
        "avg_speed_off",
        "avg_speed_def",
    ],
    "shooting": [
        "date",
        "team",
        "fgm_ra",
        "fga_ra",
        "fg_pct_ra",
        "fgm_paint",
        "fga_paint",
        "fg_pct_paint",
        "fgm_mr",
        "fga_mr",
        "fg_pct_mr",
        "fgm_lc3",
        "fga_lc3",
        "fg_pct_lc3",
        "fgm_rc3",
        "fga_rc3",
        "fg_pct_rc3",
        "fgm_c3",
        "fga_c3",
        "fg_pct_c3",
        "fgm_atb3",
        "fga_atb3",
        "fg_pct_atb3",
    ],
    "opponent_shooting": [
        "date",
        "team",
        "opp_fgm_ra",
        "opp_fga_ra",
        "opp_fg_pct_ra",
        "opp_fgm_paint",
        "opp_fga_paint",
        "opp_fg_pct_paint",
        "opp_fgm_mr",
        "opp_fga_mr",
        "opp_fg_pct_mr",
        "opp_fgm_lc3",
        "opp_fga_lc3",
        "opp_fg_pct_lc3",
        "opp_fgm_rc3",
        "opp_fga_rc3",
        "opp_fg_pct_rc3",
        "opp_fgm_c3",
        "opp_fga_c3",
        "opp_fg_pct_c3",
        "opp_fgm_atb3",
        "opp_fga_atb3",
        "opp_fg_pct_atb3",
    ],
    "hustle": [
        "date",
        "team",
        "screen_ast",
        "screen_ast_pts",
        "deflections",
        "off_loose_ball_rec",
        "def_loose_ball_rec",
        "loose_ball_rec",
        "pct_loose_ball_rec_off",
        "pct_loose_ball_rec_def",
        "charges_drawn",
        "contested_2pt",
        "contested_3pt",
        "contested_shots",
    ],
}

URL_POSTFIX = {
    "traditional": "dashteamstats",
    "advanced": "dashteamstats",
    "four_factors": "dashteamstats",
    "misc": "dashteamstats",
    "scoring": "dashteamstats",
    "opponent": "dashteamstats",
    "speed_distance": "dashptstats",
    "shooting": "dashteamshotlocations",
    "opponent_shooting": "dashteamshotlocations",
    "hustle": "hustlestatsteam",
}

PARAMS = {
    "traditional": {
        "Conference": "",
        "DateFrom": "",
        "DateTo": "",
        "Division": "",
        "GameScope": "",
        "GameSegment": "",
        "LastNGames": "0",
        "LeagueID": "00",
        "Location": "",
        "MeasureType": "Base",
        "Month": "0",
        "OpponentTeamID": "0",
        "Outcome": "",
        "PORound": "0",
        "PaceAdjust": "N",
        "PerMode": "PerGame",
        "Period": "0",
        "PlayerExperience": "",
        "PlayerPosition": "",
        "PlusMinus": "N",
        "Rank": "N",
        "Season": "",
        "SeasonSegment": "",
        "SeasonType": "Regular Season",
        "ShotClockRange": "",
        "StarterBench": "",
        "TeamID": "0",
        "TwoWay": "0",
        "VsConference": "",
        "VsDivision": "",
    },
    "advanced": {
        "Conference": "",
        "DateFrom": "",
        "DateTo": "",
        "Division": "",
        "GameScope": "",
        "GameSegment": "",
        "LastNGames": "0",
        "LeagueID": "00",
        "Location": "",
        "MeasureType": "Advanced",
        "Month": "0",
        "OpponentTeamID": "0",
        "Outcome": "",
        "PORound": "0",
        "PaceAdjust": "N",
        "PerMode": "PerGame",
        "Period": "0",
        "PlayerExperience": "",
        "PlayerPosition": "",
        "PlusMinus": "N",
        "Rank": "N",
        "Season": "",
        "SeasonSegment": "",
        "SeasonType": "Regular Season",
        "ShotClockRange": "",
        "StarterBench": "",
        "TeamID": "0",
        "TwoWay": "0",
        "VsConference": "",
        "VsDivision": "",
    },
    "four_factors": {
        "Conference": "",
        "DateFrom": "",
        "DateTo": "",
        "Division": "",
        "GameScope": "",
        "GameSegment": "",
        "LastNGames": "0",
        "LeagueID": "00",
        "Location": "",
        "MeasureType": "Four Factors",
        "Month": "0",
        "OpponentTeamID": "0",
        "Outcome": "",
        "PORound": "0",
        "PaceAdjust": "N",
        "PerMode": "PerGame",
        "Period": "0",
        "PlayerExperience": "",
        "PlayerPosition": "",
        "PlusMinus": "N",
        "Rank": "N",
        "Season": "",
        "SeasonSegment": "",
        "SeasonType": "Regular Season",
        "ShotClockRange": "",
        "StarterBench": "",
        "TeamID": "0",
        "TwoWay": "0",
        "VsConference": "",
        "VsDivision": "",
    },
    "misc": {
        "Conference": "",
        "DateFrom": "",
        "DateTo": "",
        "Division": "",
        "GameScope": "",
        "GameSegment": "",
        "LastNGames": "0",
        "LeagueID": "00",
        "Location": "",
        "MeasureType": "Misc",
        "Month": "0",
        "OpponentTeamID": "0",
        "Outcome": "",
        "PORound": "0",
        "PaceAdjust": "N",
        "PerMode": "PerGame",
        "Period": "0",
        "PlayerExperience": "",
        "PlayerPosition": "",
        "PlusMinus": "N",
        "Rank": "N",
        "Season": "",
        "SeasonSegment": "",
        "SeasonType": "Regular Season",
        "ShotClockRange": "",
        "StarterBench": "",
        "TeamID": "0",
        "TwoWay": "0",
        "VsConference": "",
        "VsDivision": "",
    },
    "scoring": {
        "Conference": "",
        "DateFrom": "",
        "DateTo": "",
        "Division": "",
        "GameScope": "",
        "GameSegment": "",
        "LastNGames": "0",
        "LeagueID": "00",
        "Location": "",
        "MeasureType": "Scoring",
        "Month": "0",
        "OpponentTeamID": "0",
        "Outcome": "",
        "PORound": "0",
        "PaceAdjust": "N",
        "PerMode": "PerGame",
        "Period": "0",
        "PlayerExperience": "",
        "PlayerPosition": "",
        "PlusMinus": "N",
        "Rank": "N",
        "Season": "",
        "SeasonSegment": "",
        "SeasonType": "Regular Season",
        "ShotClockRange": "",
        "StarterBench": "",
        "TeamID": "0",
        "TwoWay": "0",
        "VsConference": "",
        "VsDivision": "",
    },
    "opponent": {
        "Conference": "",
        "DateFrom": "",
        "DateTo": "",
        "Division": "",
        "GameScope": "",
        "GameSegment": "",
        "LastNGames": "0",
        "LeagueID": "00",
        "Location": "",
        "MeasureType": "Opponent",
        "Month": "0",
        "OpponentTeamID": "0",
        "Outcome": "",
        "PORound": "0",
        "PaceAdjust": "N",
        "PerMode": "PerGame",
        "Period": "0",
        "PlayerExperience": "",
        "PlayerPosition": "",
        "PlusMinus": "N",
        "Rank": "N",
        "Season": "",
        "SeasonSegment": "",
        "SeasonType": "Regular Season",
        "ShotClockRange": "",
        "StarterBench": "",
        "TeamID": "0",
        "TwoWay": "0",
        "VsConference": "",
        "VsDivision": "",
    },
    "speed_distance": {
        "College": "",
        "Conference": "",
        "Country": "",
        "DateFrom": "",
        "DateTo": "",
        "Division": "",
        "DraftPick": "",
        "DraftYear": "",
        "GameScope": "",
        "GameSegment": "",
        "Height": "",
        "LastNGames": "0",
        "LeagueID": "00",
        "Location": "",
        "Month": "0",
        "OpponentTeamID": "0",
        "Outcome": "",
        "PORound": "0",
        "PerMode": "PerGame",
        "Period": "0",
        "PlayerExperience": "",
        "PlayerOrTeam": "Team",
        "PlayerPosition": "",
        "PtMeasureType": "SpeedDistance",
        "Season": "",
        "SeasonSegment": "",
        "SeasonType": "Regular Season",
        "StarterBench": "",
        "TeamID": "0",
        "VsConference": "",
        "VsDivision": "",
        "Weight": "",
    },
    "shooting": {
        "Conference": "",
        "DateFrom": "",
        "DateTo": "",
        "DistanceRange": "By Zone",
        "Division": "",
        "GameScope": "",
        "GameSegment": "",
        "LastNGames": "0",
        "LeagueID": "00",
        "Location": "",
        "MeasureType": "Base",
        "Month": "0",
        "OpponentTeamID": "0",
        "Outcome": "",
        "PORound": "0",
        "PaceAdjust": "N",
        "PerMode": "PerGame",
        "Period": "0",
        "PlayerExperience": "",
        "PlayerPosition": "",
        "PlusMinus": "N",
        "Rank": "N",
        "Season": "",
        "SeasonSegment": "",
        "SeasonType": "Regular Season",
        "ShotClockRange": "",
        "StarterBench": "",
        "TeamID": "0",
        "TwoWay": "0",
        "VsConference": "",
        "VsDivision": "",
    },
    "opponent_shooting": {
        "Conference": "",
        "DateFrom": "",
        "DateTo": "",
        "DistanceRange": "By Zone",
        "Division": "",
        "GameScope": "",
        "GameSegment": "",
        "LastNGames": "0",
        "LeagueID": "00",
        "Location": "",
        "MeasureType": "Opponent",
        "Month": "0",
        "OpponentTeamID": "0",
        "Outcome": "",
        "PORound": "0",
        "PaceAdjust": "N",
        "PerMode": "PerGame",
        "Period": "0",
        "PlayerExperience": "",
        "PlayerPosition": "",
        "PlusMinus": "N",
        "Rank": "N",
        "Season": "",
        "SeasonSegment": "",
        "SeasonType": "Regular Season",
        "ShotClockRange": "",
        "StarterBench": "",
        "TeamID": "0",
        "VsConference": "",
        "VsDivision": "",
    },
    "hustle": {
        "College": "",
        "Conference": "",
        "Country": "",
        "DateFrom": "",
        "DateTo": "",
        "Division": "",
        "DraftPick": "",
        "DraftYear": "",
        "GameScope": "",
        "GameSegment": "",
        "Height": "",
        "LastNGames": "0",
        "LeagueID": "00",
        "Location": "",
        "Month": "0",
        "OpponentTeamID": "0",
        "Outcome": "",
        "PORound": "0",
        "PaceAdjust": "N",
        "PerMode": "PerGame",
        "Period": "0",
        "PlayerExperience": "",
        "PlayerPosition": "",
        "PlusMinus": "N",
        "Rank": "N",
        "Season": "",
        "SeasonSegment": "",
        "SeasonType": "Regular Season",
        "ShotClockRange": "",
        "TeamID": "0",
        "VsConference": "",
        "VsDivision": "",
        "Weight": "",
    },
}

DATA_ROWS = {
    "traditional": [
        1,
        2,
        3,
        4,
        5,
        6,
        26,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        27,
    ],
    "advanced": [1, 8, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 26, 25],
    "four_factors": [1, 8, 11, 12, 13, 14],
    "misc": [1, 7, 8, 9, 10, 11, 12, 13, 14],
    "scoring": [1, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
    "opponent": [
        1,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
    ],
    "speed_distance": [2, 8, 9, 10, 11, 12, 13, 14],
    "shooting": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        23,
        24,
        25,
        17,
        18,
        19,
    ],
    "opponent_shooting": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        23,
        24,
        25,
        17,
        18,
        19,
    ],
    "hustle": [1, 8, 9, 6, 10, 11, 12, 13, 14, 7, 4, 5, 3],
}
