artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/743cc4c14cc64cf0ab95cb5e9a25db59/artifacts
end_time: 1662486882733
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 743cc4c14cc64cf0ab95cb5e9a25db59
run_uuid: 743cc4c14cc64cf0ab95cb5e9a25db59
source_name: ''
source_type: 4
source_version: ''
start_time: 1662485181641
status: 3
tags: []
user_id: jeff
