artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/8a5b1a2866cd472e92eaa3398f90984d/artifacts
end_time: 1662449857822
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 8a5b1a2866cd472e92eaa3398f90984d
run_uuid: 8a5b1a2866cd472e92eaa3398f90984d
source_name: ''
source_type: 4
source_version: ''
start_time: 1662449857763
status: 3
tags: []
user_id: jeff
