artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/d47d5416db55479c939b3b84618c34a0/artifacts
end_time: 1662486170105
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: d47d5416db55479c939b3b84618c34a0
run_uuid: d47d5416db55479c939b3b84618c34a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486170024
status: 3
tags: []
user_id: jeff
