artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/2c39f9f0123447bdb36258523b38a1e8/artifacts
end_time: 1662449858292
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 2c39f9f0123447bdb36258523b38a1e8
run_uuid: 2c39f9f0123447bdb36258523b38a1e8
source_name: ''
source_type: 4
source_version: ''
start_time: 1662449858234
status: 3
tags: []
user_id: jeff
