artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/187cf8e1b16248df93d8031513856d3d/artifacts
end_time: 1662486170419
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 187cf8e1b16248df93d8031513856d3d
run_uuid: 187cf8e1b16248df93d8031513856d3d
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486170366
status: 3
tags: []
user_id: jeff
