artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/12fe52b4a0eb4966891e88fc80842870/artifacts
end_time: 1662486170268
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 12fe52b4a0eb4966891e88fc80842870
run_uuid: 12fe52b4a0eb4966891e88fc80842870
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486170212
status: 3
tags: []
user_id: jeff
