artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/be8535bea252477eb87c13ba1dd0a895/artifacts
end_time: 1662486168866
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: be8535bea252477eb87c13ba1dd0a895
run_uuid: be8535bea252477eb87c13ba1dd0a895
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486168633
status: 3
tags: []
user_id: jeff
