artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/cf2c5d737b7541e9ab2aceab2ffb0582/artifacts
end_time: 1662486169904
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: cf2c5d737b7541e9ab2aceab2ffb0582
run_uuid: cf2c5d737b7541e9ab2aceab2ffb0582
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486169842
status: 3
tags: []
user_id: jeff
