artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/e648412927c640a9aaebfc6fea54ddae/artifacts
end_time: 1662486170608
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: e648412927c640a9aaebfc6fea54ddae
run_uuid: e648412927c640a9aaebfc6fea54ddae
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486170547
status: 3
tags: []
user_id: jeff
