artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/422e88ee9e32444785be28974e650f38/artifacts
end_time: 1662485181639
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 422e88ee9e32444785be28974e650f38
run_uuid: 422e88ee9e32444785be28974e650f38
source_name: ''
source_type: 4
source_version: ''
start_time: 1662448435012
status: 3
tags: []
user_id: jeff
