from scrapy import Field, Item


class BR_StandingsItem(Item):
    date = Field()
    team = Field()
    wins = Field()
    losses = Field()
    win_perc = Field()
    points_scored_per_game = Field()
    points_allowed_per_game = Field()
    expected_wins = Field()
    expected_losses = Field()


class BR_TeamStatsItem(Item):
    date = Field()
    team = Field()
    g = Field()
    mp = Field()
    fg = Field()
    fga = Field()
    fg_pct = Field()
    fg3 = Field()
    fg3a = Field()
    fg3_pct = Field()
    fg2 = Field()
    fg2a = Field()
    fg2_pct = Field()
    ft = Field()
    fta = Field()
    ft_pct = Field()
    orb = Field()
    drb = Field()
    trb = Field()
    ast = Field()
    stl = Field()
    blk = Field()
    tov = Field()
    pf = Field()
    pts = Field()


class BR_OpponentStatsItem(Item):
    date = Field()
    team = Field()
    opp_g = Field()
    opp_mp = Field()
    opp_fg = Field()
    opp_fga = Field()
    opp_fg_pct = Field()
    opp_fg3 = Field()
    opp_fg3a = Field()
    opp_fg3_pct = Field()
    opp_fg2 = Field()
    opp_fg2a = Field()
    opp_fg2_pct = Field()
    opp_ft = Field()
    opp_fta = Field()
    opp_ft_pct = Field()
    opp_orb = Field()
    opp_drb = Field()
    opp_trb = Field()
    opp_ast = Field()
    opp_stl = Field()
    opp_blk = Field()
    opp_tov = Field()
    opp_pf = Field()
    opp_pts = Field()
