artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/678f47b0e87a47ca92a92359742d17fa/artifacts
end_time: 1662449859249
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 678f47b0e87a47ca92a92359742d17fa
run_uuid: 678f47b0e87a47ca92a92359742d17fa
source_name: ''
source_type: 4
source_version: ''
start_time: 1662449859183
status: 3
tags: []
user_id: jeff
