artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/6b92ec80f7184a8b9041251c2b72c084/artifacts
end_time: 1662449860036
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 6b92ec80f7184a8b9041251c2b72c084
run_uuid: 6b92ec80f7184a8b9041251c2b72c084
source_name: ''
source_type: 4
source_version: ''
start_time: 1662449859970
status: 3
tags: []
user_id: jeff
