artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/09d5599b86ad4b129906fbb41db26a1d/artifacts
end_time: 1662449857666
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 09d5599b86ad4b129906fbb41db26a1d
run_uuid: 09d5599b86ad4b129906fbb41db26a1d
source_name: ''
source_type: 4
source_version: ''
start_time: 1662449857602
status: 3
tags: []
user_id: jeff
