artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/b40f65bd1648406b9b78b15174ea1b68/artifacts
end_time: 1662449856761
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: b40f65bd1648406b9b78b15174ea1b68
run_uuid: b40f65bd1648406b9b78b15174ea1b68
source_name: ''
source_type: 4
source_version: ''
start_time: 1662449856574
status: 3
tags: []
user_id: jeff
