artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/4701af3c23c94419bd35fa663d13085c/artifacts
end_time: 1662484743599
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 4701af3c23c94419bd35fa663d13085c
run_uuid: 4701af3c23c94419bd35fa663d13085c
source_name: ''
source_type: 4
source_version: ''
start_time: 1662484743380
status: 3
tags: []
user_id: jeff
