artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/bc1008ec27ca45afbe98bdce374daa15/artifacts
end_time: 1662486170779
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: bc1008ec27ca45afbe98bdce374daa15
run_uuid: bc1008ec27ca45afbe98bdce374daa15
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486170716
status: 3
tags: []
user_id: jeff
