artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/32b8210b3d02464ead9bcd8b4b98ed7b/artifacts
end_time: 1662486169037
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 32b8210b3d02464ead9bcd8b4b98ed7b
run_uuid: 32b8210b3d02464ead9bcd8b4b98ed7b
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486168972
status: 3
tags: []
user_id: jeff
