artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/1/4fb17bf62ed64971b90e5486feef284a/artifacts
end_time: 1662449859561
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 4fb17bf62ed64971b90e5486feef284a
run_uuid: 4fb17bf62ed64971b90e5486feef284a
source_name: ''
source_type: 4
source_version: ''
start_time: 1662449859505
status: 3
tags: []
user_id: jeff
