# If I need farther back seasons,
# I will need to find them in Covers schedule payload
# using Google Inspect Network.
COVERS_SEASON_ID = {
    "2022-2023": 3996,
    "2021-2022": 3068,
    "2020-2021": 2043,
    "2019-2020": 427,
    "2018-2019": 236,
}

COVERS_TEAM_ID = {
    "boston-celtics": 98,
    "brooklyn-nets": 92,
    "toronto-raptors": 104,
    "new-york-knicks": 81,
    "philadelphia-76ers": 86,
    "chicago-bulls": 38,
    "cleveland-cavaliers": 20,
    "detroit-pistons": 32,
    "indiana-pacers": 13,
    "milwaukee-bucks": 5,
    "atlanta-hawks": 74,
    "charlotte-hornets": 67,
    "miami-heat": 53,
    "orlando-magic": 61,
    "washington-wizards": 45,
    "denver-nuggets": 123,
    "minnesota-timberwolves": 114,
    "oklahoma-city-thunder": 118,
    "portland-trail-blazers": 134,
    "utah-jazz": 140,
    "golden-state-warriors": 183,
    "phoenix-suns": 193,
    "sacramento-kings": 198,
    "los-angeles-clippers": 188,
    "los-angeles-lakers": 175,
    "dallas-mavericks": 160,
    "houston-rockets": 150,
    "memphis-grizzlies": 146,
    "new-orleans-pelicans": 155,
    "san-antonio-spurs": 167,
}

TEAM_NAMES = {
    "boston-celtics": "BOS",
    "brooklyn-nets": "BKN",
    "toronto-raptors": "TOR",
    "new-york-knicks": "NYK",
    "philadelphia-76ers": "PHI",
    "chicago-bulls": "CHI",
    "cleveland-cavaliers": "CLE",
    "detroit-pistons": "DET",
    "indiana-pacers": "IND",
    "milwaukee-bucks": "MIL",
    "atlanta-hawks": "ATL",
    "charlotte-hornets": "CHA",
    "miami-heat": "MIA",
    "orlando-magic": "ORL",
    "washington-wizards": "WAS",
    "denver-nuggets": "DEN",
    "minnesota-timberwolves": "MIN",
    "oklahoma-city-thunder": "OKC",
    "portland-trail-blazers": "POR",
    "utah-jazz": "UTA",
    "golden-state-warriors": "GSW",
    "phoenix-suns": "PHX",
    "sacramento-kings": "SAC",
    "los-angeles-clippers": "LAC",
    "los-angeles-lakers": "LAL",
    "dallas-mavericks": "DAL",
    "houston-rockets": "HOU",
    "memphis-grizzlies": "MEM",
    "new-orleans-pelicans": "NOP",
    "san-antonio-spurs": "SAS",
}
