artifact_uri: file:///home/jeff/Documents/Data_Science_Projects/NBA_Betting/models/AutoML/2/d528b83bea1143eb8361f8023304e237/artifacts
end_time: 1662486168300
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: d528b83bea1143eb8361f8023304e237
run_uuid: d528b83bea1143eb8361f8023304e237
source_name: ''
source_type: 4
source_version: ''
start_time: 1662486168030
status: 3
tags: []
user_id: jeff
